# See https://pre-commit.com for more information
# See https://pre-commit.com/hooks.html for more hooks
default_install_hook_types: [pre-commit]
fail_fast: false
repos:
- repo: https://github.com/pre-commit/pre-commit-hooks
  rev: v6.0.0
  hooks:
  - id: trailing-whitespace
  - id: end-of-file-fixer
  - id: check-toml
  - id: check-yaml
  - id: check-added-large-files
  - id: check-merge-conflict

repos:
- repo: https://github.com/PlasmaFAIR/fortitude-pre-commit
  # Fortitude version.
  rev: v0.7.5
  hooks:
    - id: fortitude
    #   args: ["--fix", "--unsafe-fixes", "--preview"]

- repo: local
  hooks:
  - id: codee-format
    name: Codee Format
    entry: git codee-format
    language: system
    types: [file]
    files: '\.(f|F|f90|F90|f95|F95)$'

- repo: local
  hooks:
  - id: compile-fpm
    name: Test successful compilation with fpm
    entry: fpm @debug_gcc
    language: system
    pass_filenames: false
    always_run: true

# - repo: local
#   hooks:
#   - id: test-fpm
#     name: Run tests with fpm
#     entry: fpm test
#     language: system
#     pass_filenames: false
#     always_run: true
