name = "fortran-numpy-mpi"
version = "0.1.0"
license = "license"
author = "Matthew Alexandrakis"
maintainer = "10999402+MatthAlex@users.noreply.github.com"

[build]
auto-executables = true
auto-tests = true
auto-examples = true
module-naming = false

[install]
library = false

[dependencies]
mpi = "*"
stdlib = "*"

[fortran]
implicit-typing = true
implicit-external = true
source-form = "free"

[extra.fortitude.check]
# preview = true  # enables more rules - enable after formatting changes
show-fixes = true  # Enumerate all fixed violations.
line-length = 132
file-extensions = ["f90", "F90"]
ignore =[
    "S232", # Whitespace included in 'in out'
    "S271", # Unsorted imports
    "C051", # Trailing backslash (in comments)
    # "S291", # trailing decimal point in `real` literal `0._prec` ( still in preview )
]
