[project]
name = "fortran-numpy-mpi"
version = "0.1.0"
description = "Dump Euclidean 3D field data to numpy `.npy` files from MPI Fortran, then combine them easily for Python loading and manipulation."
dependencies = [
    "fpm==0.10.1",
    "matplotlib>=3.11.1",
    "numpy>=2.4.6",
]
requires-python = ">=3.11"
authors = [
  { name = "Matthew Alexandrakis", email = "10999402+MatthAlex@users.noreply.github.com" },
]
readme = "README.md"
license = { file = "LICENSE" }
keywords = ["fortran", "modern fortran", "mpi", "numpy"]
classifiers = [
  "Development Status :: 4 - Beta",
  "Programming Language :: Modern Fortran",
  "Programming Language :: Python",
]

[project.optional-dependencies]
dev = [
    "fortls",
    "pre-commit",
    "fortitude-lint",
]
